### ISSUE TITLE
Fix: Font color in the homepage

### ISSUE THREAD

**Issue by S-125** [gfgkare/gfgkare.github.io#3]
![image](https://github.com/user-attachments/assets/efe0bc0a-f0df-4427-8d32-6b1506f89273)
The font color is almost blending with the background. I want to fix this issue and add some text outline to give it a 3d look . Please assign me this under hacktoberfest

**Comment by gfgkare** [comment]
Thank you so much for your interest @S-125, but this is fixed already in fa5548aaff7
